### ISSUE TITLE
Use transifex for translations

### ISSUE THREAD

**Issue by glixx** [ArtOfIllusion/ArtOfIllusion#119]
There is transifex.com. It's free for open source projects. It support Java properties format.

**Comment by Sailsman63** [comment]
Transifex is intended to help big teams keep coordinated. AOI rarely has much change in UI text. What gains for _this_ project would you expect?

**Comment by glixx** [comment]
It will help translators to have up to date translations. They will be informed about new strings. It would be online translations by native language, to not need applications just browser.

**Comment by Sailsman63** [comment]
I've just taken another look at Transifex. There seems to be a lot of overhead in managing a translation team, and anyone who wants to contribute also needs to set up an account.

Since AOI Translations are a *single file* I don't want to deal with that overhead.
If anyone has a strong reason to disagree, I'd be glad to hear it.
