### ISSUE TITLE
Hide Objects List panel command is not work

### ISSUE THREAD

**Issue by makiam** [ArtOfIllusion/ArtOfIllusion#31]
The problem has two parts:
First one: menu selection code expects that command is under Scene menu. It's easy to fix.

Second one: the proper visibility toggling depends on other panel under same dock. If we detach Properties panel from dock toggling begin to work. If we move score panel to  right dock toggling for Objects panel fails and in this case toggling Score panel becomes invalid too

**Comment by Sailsman63** [comment]
Thanks for reminding me of this. The first part is, as you stated, easy to fix.

The Second part has actually been the case for some time. Not as simple to fix. @peastman I think that this has been a problem since object properties were added as a dockable widget.

**Comment by peastman** [comment]
I'm not sure how much sense that command even makes anymore.  It used to just adjust the position of the divider.  But now that there could be multiple panels in the same group, what should it do?

**Comment by Sailsman63** [comment]
Not sure if we still need it. If we fix & keep, it should be re-named and it should apply to that whole group.

In testing, I found that the `setObjectListVisible()` method functions as expected, but that when there is more than one panel in the group, the command processor and the menu update cannot detect that the group is already hidden.

The buoy code here seems a bit convoluted, and I admit that I have not yet graphed out how all the components come together.

**Comment by Sailsman63** [comment]
Are we okay with just removing this?

Given the lack of support requests on the subject, the average AOI user never notices that this exists. The reports that we have received all came from tech-y people who the to exhaustively test everything in the UI, even if they don't really use it.

If it's not used, is just taking up menu space, and broken UI elements give a bad impression.

**Comment by peteihis** [comment]
Hey, my bad... The first part I mean. (Sorry I did not originally understant, what this was about.)

I forgot to move the command to the viewMenu block. Usually 3D-software have the option of hiding side panels, and since the command is there, I'd suggest to keep it. I can push a fix tonight. The command is necessary, because some plugin-added items (=Preview) in the panel can not be hidden by dragging the edge of the panel.

But (call it '#1b'): I suppose the expectation to be, that you could get the side panel out of hiding by the same menu item? Have to look what it takes, if I can come up something simple...)

And '#1c': The name should probably be something like "Hide side panel".

Looking at the code now, I'm wondering if it actually is necessary to have the menu recognized on the `actionPerformed()`? I'd expect the commands have the same effect, where ever they come form? Just have a long switch in there to handle all of them?

The 2nd part (and what ever parts may follow that) is a bigger remake. I remember, that about a year and a half ago I was trying to understand how everything works there, and it looked really confusing and the confusion does not stop there. If you move the sub panels around the main window a bit, it begins to be very difficult to get everything back. 

The third part which actually matters is, that, when the object list gets very long, I like to undock it (and I know, I'm not the only one who does that) but then keyboard commands on the object list (Ctrl+C, Ctrl+V, backspace delete...) don't work . -- And that is not the only weird thing about the object list. I guess it would have to be one of the oldest parts of AoI, so may be we should consider a small upgrade? :)

I suppose nobody complains about this, because they have learned the hard way not to mess with the panels ....

**Comment by peteihis** [comment]
See my comments in the PR.
