### ISSUE TITLE
Button issue with Purging images

### ISSUE THREAD

**Issue by Sailsman63** [ArtOfIllusion/ArtOfIllusion#49]
The new purge feature, added in #35, does not properly reset the image dialog buttons when the selected image is deleted. Buttons such as "See Details" are still active, which can lead to a `Null Pointer Exception`

I'd like to see the entire button panel streamlined, but will wait for user feedback on the new feature.

**Comment by peteihis** [comment]
> does not properly reset the image dialog buttons when the selected image is deleted

Actually it does'n matter if the selected image was among the deted or not. What happens is that purge sets none selected, but the state of the buttons is not updates, so if the button was active before purge, it tries to open details the details window without an image... 

The fix is to add `hilightButtons` as the last statement in `private void purge()`, lines 249 - 254.

I found another little gitch too. If you try to open an file with the extension `.hdr` and the file is something else there is an uncaught error, that will interrupt the loading. It interrups a multimple image load too, without loading anything.

The error should be handled so, that the images, that can be loaded would still be loaded and the user is notified about those that were not.

**Comment by peteihis** [comment]
> The error should be handled so, that the images, that can be loaded would still be loaded and the user is notified about those that were not.

Got that. Removed `return` from the `catch` block. That unnecessrily interrupted the entire loading process.

**Q:** Does it make any sense to `printStackTrace()` in cases like this. We know where the error happened and the output tells very little (or the way I see it , nothing) of, what was wrong with the file. The listed command-chain through all the java-libraries is hardly anything that helps or that we could do anything about.
